title: The VBTC Blog
author: VBTC
email: info@vbtc.vn
description: News and announcements regarding VBTC, the first Bitcoin live exchange in Vietnam
baseurl: "/"
url: "https://vbtc.github.io"
show_excerpts: true

twitter_username: vbtc_vietnam
facebook_username: VBTC.vn
github_username: vbtc
rss: feed.xml

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - .idea/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/